config/routes.rb
Rails.application.routes.draw do
  get '/:list_name/', to: 'messages#index', as: :list
  resources :list, only: [], path: '', param: :name do
    resources :messages, only: :show, path: '', param: :list_seq
  end
  get '/attachments/:encoded_key/*filename' => 'attachments#show', as: :attachment

  get '/messages/search_all', to: 'messages#search_all', as: :search_all_messages

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'messages#index'
end

app/models/message.rb
BLADE_BUCKET_REGION = 'ap-northeast-1'
BLADE_BUCKET_NAME = 'blade-data-vault'

require 'kconv'

class Message < ApplicationRecord
  class PartialSkipped < StandardError
  end
  class PartialSaved < StandardError
  end

  # Not really sure we will utlize this configuration,
  # but I don't want to make this column.
  # https://blade.ruby-lang.org/ruby-talk/1 is JST.
  # https://blade.ruby-lang.org/ruby-talk/410000 is not.
  self.skip_time_zone_conversion_for_attributes = [:published_at]

  has_many_attached :attachments

  attr_accessor :children

  class << self
    def from_mail(mail, list, list_seq)
      new.from_mail(mail, list, list_seq)
    end
  end

  def from_mail(mail, list, list_seq)
    self.list_id, self.list_seq, self.published_at = list.id, list_seq, mail.date

    handle_body mail

    if ((list.name == 'ruby-dev') && list_seq.in?([13859, 26229, 39731, 39734])) || ((list.name == 'ruby-core') && list_seq.in?([5231])) || ((list.name == 'ruby-list') && list_seq.in?([29637, 29711, 30148])) || ((list.name == 'ruby-talk') && list_seq.in?([5198, 61316]))
      self.body.gsub!("\u0000", '')
    end

    if (list.name == 'ruby-list') && list_seq.in?([37565, 38116, 43106])
      mail.header[:subject].value.chop!
    end
    if (list.name == 'ruby-list') && (list_seq.in?([41850, 43710]))
      mail.header[:subject].value = Kconv.toutf8 mail.header[:subject].value
    end
    self.subject = mail.subject
    self.subject = Kconv.toutf8 subject if self.subject

    self.from = mail.from_address&.raw
    self.from = Kconv.toutf8 from if from
    if !from && (list.name == 'ruby-core') && (list_seq == 161)
      self.from = mail.from.encode Encoding::UTF_8, Encoding::KOI8_R
    end

    self.message_id_header = mail.message_id&.encode Encoding::UTF_8, invalid: :replace, undef: :replace

    # mail.in_reply_to returns strange Array object in some cases (?), so let's use the raw value
    parent_message_id_header = extract_message_id_from_in_reply_to(mail.header[:in_reply_to]&.value)
    self.parent_id = Message.where(list_id: list, message_id_header: parent_message_id_header).pick(:id) if parent_message_id_header
    if !self.parent_id && (String === mail.references)
      self.parent_id = Message.where(list_id: list, message_id_header: mail.references).pick(:id)
    end
    if !self.parent_id && (Array === mail.references)
      mail.references.compact.each do |ref|
        break if (self.parent_id = Message.where(list_id: list, message_id_header: ref).pick(:id))
      end
    end

    self.yyyymm = self.published_at.strftime('%Y%m')

    self
  end

  private def handle_body(part)
    if part.multipart?
      part.parts.each do |p|
        handle_body p
      end
    elsif part.attachment?
      file = StringIO.new(part.decoded)
      attachments.attach(io: file, filename: part.filename, content_type: part.content_type)
    else
      case part.content_type&.downcase
      when 'application/pgp-signature'
        # ignore
      when 'application/ms-tnef'
        file = StringIO.new(part.decoded)
        attachments.attach(io: file, filename: part.filename || 'noname', content_type: part.content_type)
      when /^text\/plain/, /text\/enriched;/, 'message/rfc822', nil
        # body.decoded: handles Content-Transfer-Encoding (base64, quoted-printable)
        # Kconv.toutf8: auto-detects charset (handles mislabeled charsets in legacy emails)
        (self.body ||= ''.dup) << Kconv.toutf8(part.body.decoded)
      when /^text\/html/
        (self.html_body ||= ''.dup) << Kconv.toutf8(part.body.decoded)
      when 'application/octet-stream', 'image/gif', 'application/rtf', 'message/delivery-status'
        # there can be an attachment with nil part.filename (which is equivalent to part.attachment?).
        file = StringIO.new(part.decoded)
        attachments.attach(io: file, filename: part.filename || 'noname', content_type: part.content_type)
      when /message\/partial; id="(?<id>.*?)"; number=(?<number>\d); total=(?<total>\d)/
        # message/partial; id=\"Wed_Dec_22_02:43:22_1999@debian\"; number=2; total=2
        match = Regexp.last_match
        if match[:number] == match[:total]
          previous_partials = $partials[match[:id]]
          first_partial = previous_partials.first
          body = previous_partials.each_with_object(''.dup) { |msg, str| str << msg.body } << part.body.raw_source
          str = Kconv.toutf8 body
          mail = Mail.read_from_string str
          message = self.class.from_mail mail, first_partial.list, first_partial.list_seq
          message.save!
          $partials = {}

          raise PartialSkipped
        else
          self.body = part.body.raw_source
          (($partials ||= {})[match[:id]] ||= []) << self
          raise PartialSaved
        end
      else
        raise "Unknown content_type: #{part.content_type}"
      end
    end
  end

  private def extract_message_id_from_in_reply_to(header)
    header && header.strip.scan(/<([^>]+)>/).flatten.first
  end

  class << self
    def from_s3(list, list_seq, s3_client = Aws::S3::Client.new(region: BLADE_BUCKET_REGION))
      begin
        obj = s3_client.get_object(bucket: BLADE_BUCKET_NAME, key: "#{list.name}/#{list_seq}")
      rescue Aws::S3::Errors::NoSuchKey
        p "#{list.name}:#{list_seq} doesn't exist in S3"
        return
      end
      str = obj.body.read.force_encoding(Encoding::BINARY)
      if str.blank?
        p "#{list.name}:#{list_seq} is empty"
        return
      end
      mail = Mail.read_from_string str
      Message.from_mail mail, list, list_seq
    end

    def from_string(str)
      # There are a few hacks to import messages from blade.ruby-lang.org's
      # S3 bucket.

      # Need to call String#b. There are messages that have headers in non-UTF8,
      # but the body is in UTF-8, such as ruby-list:2882.
      headers_str, body = str.b.split(/\n\n/, 2)

      # ruby-list:2840 doesn't have a proper From header.
      headers_str = Kconv.toutf8(headers_str).gsub(/\r\n/, '')

      headers = headers_str.split(/\n/).map { |line|
        line.split(/:\s+/, 2)
      }.to_h

      published_at = DateTime.strptime(headers['Date'], '%Y-%m-%dT%H:%M:%S%:z')

      self.new(
        body: Kconv.toutf8(body),
        subject: headers['Subject'],
        from: headers['From'],
        published_at: published_at,
      )
    end
  end

  def list
    @list ||= List.find(list_id)
  end

  def to_param
    #NOTE: This value isn't unique system-wide. Ideally, this should return a combination of list_name and list_seq
    list_seq
  end

  def count_recursively(count = 0)
    count + 1 + (children&.sum(&:count_recursively) || 0)
  end

  def reload_from_s3(s3_client = Aws::S3::Client.new(region: BLADE_BUCKET_REGION))
    m = Message.from_s3(List.find(self.list_id), self.list_seq, s3_client)

    self.body = m.body
    self.subject = m.subject
    self.from = from
    self.published_at = m.published_at

    m
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  PER_PAGE = 50

  # GET /ruby-dev
  def index(list_name: nil, yyyymm: nil, q: nil)
    yyyymm = yyyymm&.to_i
    if list_name
      @list = List.find_by_name list_name

      render_threads yyyymm: yyyymm, q: q
    else
      redirect_to List.find_by_name('ruby-core')
    end
  end

  # GET /messages/search_all
  def search_all(q: nil, page: nil)
    if q
      search q, page
    else
      @messages = []
    end
  end

  # GET /ruby-dev/1
  def show(list_name:, list_seq:)
    @list = List.find_by_name(list_name)
    @message = Message.find_by!(list_id: @list, list_seq: list_seq)

    # Calculate navigation links
    calculate_navigation_links

    # If this is a turbo frame request, just render the message
    return if turbo_frame_request?

    render_threads yyyymm: @message.yyyymm
  end

  private

  def calculate_navigation_links
    # Find root of current thread (cached)
    root_id = Rails.cache.fetch("message:#{@message.id}:root_id") do
      root = @message
      root = Message.find(root.parent_id) while root.parent_id
      root.id
    end

    # Find previous/next thread (root messages)
    @prev_thread_seq = Message.where(list_id: @list, parent_id: nil).where('id < ?', root_id).order(id: :desc).pick(:list_seq)
    @next_thread_seq = Message.where(list_id: @list, parent_id: nil).where('id > ?', root_id).order(:id).pick(:list_seq)

    # Get all messages in this thread (cached)
    thread_messages = Rails.cache.fetch("thread:#{root_id}:messages") do
      Message.with_recursive(
        thread_msgs: [
          Message.where(id: root_id),
          Message.joins('inner join thread_msgs on messages.parent_id = thread_msgs.id')
        ]
      ).joins('inner join thread_msgs on thread_msgs.id = messages.id').order(:id).pluck(:id, :list_seq)
    end

    # Find previous/next message in thread
    current_index = thread_messages.index {|(id, _)| id == @message.id }
    @prev_message_in_thread_seq = thread_messages[current_index - 1]&.last if current_index && current_index > 0
    @next_message_in_thread_seq = thread_messages[current_index + 1]&.last if current_index
  end

  def render_threads(yyyymm: nil, q: nil)
    root_query = Message.where(list_id: @list, parent_id: nil).order(:id)

    if q
      root_query.where!('body %> ?', q)
    else
      # Cache YYYYMM list per mailing list
      @yyyymms = Rails.cache.fetch("list:#{@list.id}:yyyymms") do
        Message.distinct.where(list_id: @list, parent_id: nil).order('yyyymm').pluck('yyyymm')
      end
      @yyyymm = yyyymm || @yyyymms.last
      root_query.where!(yyyymm: @yyyymm)
    end

    messages = Message.with_recursive(parent_and_children: [root_query, Message.joins('inner join parent_and_children on messages.parent_id = parent_and_children.id')])
      .joins('inner join parent_and_children on parent_and_children.id = messages.id')

    @messages = compose_tree(messages)

    if q
      @yyyymms = @messages.map { it.yyyymm }.uniq
      @yyyymm = @yyyymms.last
    end

    render :index
  end

  def search(query, page)
    lists = List.all.select { params[it.name] != '0' }
    raise "Need to select at least one list" if lists.empty?

    # %> and <-> are defined by pg_trgm.
    # https://www.postgresql.org/docs/17/pgtrgm.html
    message_where = Message.where('body %> ? AND list_id IN (?)', query, lists.map(&:id)).order(Arel.sql('body <-> ?', query))
    @messages = message_where.offset(page.to_i * PER_PAGE).limit(PER_PAGE)
  end

  def compose_tree(messages)
    [].tap do |ret|
      messages.each do |m|
        if m.parent_id && (parent = messages.detect { it.id == m.parent_id })
          (parent.children ||= []) << m
        else
          ret << m
        end
      end
      ret.sort_by!(&:id)
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def without_list_prefix(subject)
    subject&.sub(/^\[.+?\]\s*/, '')
  end

  MARGIN = 50
  def search_snippet(body, keyword)
    snippet = ''

    offset = 0
    while (i = body.index(keyword, offset))
      start = [i - MARGIN, offset].max
      len = keyword.length + MARGIN
      snippet += body[start, len]
      offset = start + len
    end

    if snippet.empty?
      return body[0, MARGIN * 2]
    else
      snippet
    end
  end
end

app/views/messages/_attachment.html.erb
<% if attachment.content_type&.start_with?('image/') %>
  <div class="space-y-2">
    <div class="flex items-center gap-3 text-sm">
      <svg class="w-4 h-4 text-gray-400 dark:text-gray-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
      </svg>
      <%= link_to attachment.filename.to_s, rails_blob_path(attachment, disposition: "attachment"), class: "text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 font-medium" %>
      <span class="text-gray-500 dark:text-gray-400">(<%= number_to_human_size(attachment.byte_size) %>)</span>
    </div>
    <%= image_tag rails_blob_path(attachment), class: "max-w-full h-auto rounded border border-gray-300 dark:border-gray-600", alt: attachment.filename.to_s %>
  </div>
<% elsif attachment.content_type&.start_with?('text/') %>
  <div class="space-y-2">
    <div class="flex items-center gap-3 text-sm">
      <svg class="w-4 h-4 text-gray-400 dark:text-gray-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
      </svg>
      <%= link_to attachment.filename.to_s, rails_blob_path(attachment, disposition: "attachment"), class: "text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 font-medium" %>
      <span class="text-gray-500 dark:text-gray-400">(<%= number_to_human_size(attachment.byte_size) %>, <%= attachment.content_type %>)</span>
    </div>
    <% if attachment.byte_size < 100_000 %>
      <pre class="whitespace-pre-wrap font-mono text-sm text-gray-800 dark:text-gray-300 bg-gray-100 dark:bg-gray-800 p-4 rounded border border-gray-300 dark:border-gray-600 overflow-x-auto"><%= attachment.download %></pre>
    <% end %>
  </div>
<% elsif attachment.content_type == 'application/pdf' %>
  <div class="flex items-center gap-3 text-sm">
    <svg class="w-4 h-4 text-red-500 dark:text-red-400 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path>
    </svg>
    <%= link_to attachment.filename.to_s, rails_blob_path(attachment, disposition: "attachment"), class: "text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 font-medium" %>
    <span class="text-gray-500 dark:text-gray-400">(<%= number_to_human_size(attachment.byte_size) %>, PDF)</span>
  </div>
<% elsif attachment.content_type&.match?(/zip|tar|gzip|compress|bzip|lha/) %>
  <div class="flex items-center gap-3 text-sm">
    <svg class="w-4 h-4 text-gray-400 dark:text-gray-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 19a2 2 0 01-2-2V7a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1M5 19h14a2 2 0 002-2v-5a2 2 0 00-2-2H9a2 2 0 00-2 2v5a2 2 0 01-2 2z"></path>
    </svg>
    <%= link_to attachment.filename.to_s, rails_blob_path(attachment, disposition: "attachment"), class: "text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 font-medium" %>
    <span class="text-gray-500 dark:text-gray-400">(<%= number_to_human_size(attachment.byte_size) %>, Archive)</span>
  </div>
<% else %>
  <div class="flex items-center gap-3 text-sm">
    <svg class="w-4 h-4 text-gray-400 dark:text-gray-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"></path>
    </svg>
    <%= link_to attachment.filename.to_s, rails_blob_path(attachment, disposition: "attachment"), class: "text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 font-medium" %>
    <span class="text-gray-500 dark:text-gray-400">(<%= number_to_human_size(attachment.byte_size) %><% if attachment.content_type %>, <%= attachment.content_type %><% end %>)</span>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-200 dark:border-gray-700 overflow-hidden" id="<%= dom_id message %>" data-list-seq="<%= message.list_seq %>">
  <div class="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 px-6 py-4">
    <h2 class="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3"><%= message.subject %></h2>
    <div class="space-y-1 text-sm text-gray-600 dark:text-gray-400">
      <div class="flex items-center gap-2">
        <span class="font-medium text-gray-700 dark:text-gray-300">From:</span>
        <span><%= message.from %></span>
      </div>
      <div class="flex items-center gap-2">
        <span class="font-medium text-gray-700 dark:text-gray-300">Date:</span>
        <span><%= message.published_at&.strftime("%Y-%m-%d %H:%M:%S %Z") || "N/A" %></span>
      </div>
      <% if message.list %>
        <div class="flex items-center gap-2">
          <span class="font-medium text-gray-700 dark:text-gray-300">List:</span>
          <span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200">
            <%= message.list.name %> #<%= message.list_seq %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="px-6 py-4">
    <pre class="whitespace-pre-wrap font-mono text-sm text-gray-800 dark:text-gray-300 leading-relaxed"><%= message.body %></pre>
  </div>

  <% if message.attachments.attached? %>
    <div class="border-t border-gray-200 dark:border-gray-700 px-6 py-4 bg-gray-50 dark:bg-gray-900">
      <h3 class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Attachments (<%= message.attachments.count %>)</h3>
      <div class="space-y-4">
        <%= render partial: 'messages/attachment', collection: message.attachments %>
      </div>
    </div>
  <% end %>

  <% if defined?(@prev_thread_seq) || defined?(@next_thread_seq) || defined?(@prev_message_in_thread_seq) || defined?(@next_message_in_thread_seq) %>
    <div class="border-t border-gray-200 dark:border-gray-700 px-6 py-4 bg-gray-50 dark:bg-gray-900" data-controller="keyboard-nav">
      <div class="grid grid-cols-2 gap-4">
        <div>
          <h3 class="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2">Thread</h3>
          <div class="flex gap-2">
            <% if @prev_thread_seq %>
              <%= link_to list_message_path(message.list, @prev_thread_seq), class: "inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors", data: {turbo_frame: 'message_content', turbo_action: 'advance', nav: 'prev-thread'} do %>
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
                Prev
              <% end %>
            <% else %>
              <span class="inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-600 cursor-not-allowed">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
                Prev
              </span>
            <% end %>
            <% if @next_thread_seq %>
              <%= link_to list_message_path(message.list, @next_thread_seq), class: "inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors", data: {turbo_frame: 'message_content', turbo_action: 'advance', nav: 'next-thread'} do %>
                Next
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
              <% end %>
            <% else %>
              <span class="inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-600 cursor-not-allowed">
                Next
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
              </span>
            <% end %>
          </div>
        </div>
        <div>
          <h3 class="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2">In This Thread</h3>
          <div class="flex gap-2">
            <% if @prev_message_in_thread_seq %>
              <%= link_to list_message_path(message.list, @prev_message_in_thread_seq), class: "inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors", data: {turbo_frame: 'message_content', turbo_action: 'advance', nav: 'prev-message'} do %>
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
                Prev
              <% end %>
            <% else %>
              <span class="inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-600 cursor-not-allowed">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
                Prev
              </span>
            <% end %>
            <% if @next_message_in_thread_seq %>
              <%= link_to list_message_path(message.list, @next_message_in_thread_seq), class: "inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors", data: {turbo_frame: 'message_content', turbo_action: 'advance', nav: 'next-message'} do %>
                Next
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
              <% end %>
            <% else %>
              <span class="inline-flex items-center gap-1 px-3 py-2 text-sm font-medium rounded bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-600 cursor-not-allowed">
                Next
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<% content_for :title, @list.name %>

<% if notice %>
  <div class="mb-4 p-4 bg-green-50 dark:bg-green-900 border border-green-200 dark:border-green-700 text-green-800 dark:text-green-200 rounded-lg">
    <%= notice %>
  </div>
<% end %>

<div class="grid grid-cols-4 gap-6" style="height: calc(100vh - 16rem);" data-controller="message-list">
  <div class="col-span-1 overflow-y-auto space-y-6">
    <%= render partial: 'thread', collection: @messages, as: :message, locals: {list: @list, depth: 0} %>
  </div>

  <div class="col-span-3 overflow-y-auto">
    <%= turbo_frame_tag "message_content", class: "block" do %>
      <% if @message %>
        <%= render @message %>
      <% else %>
        <div class="flex items-center justify-center h-full text-gray-400 dark:text-gray-500">
          <div class="text-center">
            <svg class="w-16 h-16 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
            </svg>
            <p>Select a message to view</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<% content_for :title, @message.subject %>

<%= turbo_frame_tag 'message_content' do %>
  <% if notice %>
    <div class="mb-4 p-4 bg-green-50 dark:bg-green-900 border border-green-200 dark:border-green-700 text-green-800 dark:text-green-200 rounded-lg">
      <%= notice %>
    </div>
  <% end %>

  <%= render @message %>
<% end %>